// Code generated by MockGen. DO NOT EDIT.
// Source: rest.go
//
// Generated by this command:
//
//	mockgen -source=rest.go -destination=calculator_mock.go -package=rest
//

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"

	models "github.com/tortedCtrl/Calculator-Test-Sprint/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCalculator is a mock of Calculator interface.
type MockCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatorMockRecorder
	isgomock struct{}
}

// MockCalculatorMockRecorder is the mock recorder for MockCalculator.
type MockCalculatorMockRecorder struct {
	mock *MockCalculator
}

// NewMockCalculator creates a new mock instance.
func NewMockCalculator(ctrl *gomock.Controller) *MockCalculator {
	mock := &MockCalculator{ctrl: ctrl}
	mock.recorder = &MockCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculator) EXPECT() *MockCalculatorMockRecorder {
	return m.recorder
}

// EvalExpression mocks base method.
func (m *MockCalculator) EvalExpression(ctx context.Context, expression string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvalExpression", ctx, expression)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvalExpression indicates an expected call of EvalExpression.
func (mr *MockCalculatorMockRecorder) EvalExpression(ctx, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvalExpression", reflect.TypeOf((*MockCalculator)(nil).EvalExpression), ctx, expression)
}

// GetHistory mocks base method.
func (m *MockCalculator) GetHistory(ctx context.Context) ([]models.HistoryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx)
	ret0, _ := ret[0].([]models.HistoryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockCalculatorMockRecorder) GetHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockCalculator)(nil).GetHistory), ctx)
}
